// GET FRIEND TYPES
export const GET_FRIENDS = "GET_FRIENDS";
export const GET_FRIENDS_ERROR = "GET_FRIENDS_ERROR";
export const GET_FRIENDS_SUCCESS = "GET_FRIENDS_SUCCESS";

// CREATE FRIEND TYPES
export const CREATE_FRIEND = "CREATE_FRIEND";
export const CREATE_FRIEND_ERROR = "CREATE_FRIEND_ERROR";
export const CREATE_FRIEND_SUCCESS = "CREATE_FRIEND_SUCCESS";
